<a href="https://colab.research.google.com/github/Ambika7783/Machine-learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

import the library

In [ ]:
import numpy as np #np is my alias name

In [ ]:
arr1 = np.array([1,2,3,4,5],dtype=float) #Array is homogenous in nature
print(arr1)
print(type(arr1))
print(arr1.dtype)

[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
float64


In [ ]:
#. shape,.ndim-attributes
print(arr1.shape)#shape of array (each dimension having how many elements)
print(arr1.ndim)#Dimension of array
'''(5,)
This means:
The array has 1 dimension.
That dimension has 5 elements.
So (5,) = a 1D array with 5 elements.'''
#arr1.ndim This means the array is 1-dimensional (a vector).

(5,)
1


In [ ]:
#for zero dimension and no shape ,if we have 1 value in an array
arr0=np.array(12)
print(arr0.shape)
arr0.ndim

()


0

In [ ]:
#two dimension
arr2 = np.array([[1,2],[3,4]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)



[[1 2]
 [3 4]]
(2, 2)
2


In [ ]:
#3 dim
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(a3)
print(a3.shape)
print(a3.ndim)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
(3, 2, 3)
3


Attribute	Meaning
.ndim-Number of dimensions (axes)
.shape-Shape of array (tuple)
.size-Total elements
.dtype-Data type of elements
.itemsize-Size of one element (bytes)
.nbytes-Total memory (bytes)
.T-Transpose of array



In [ ]:
#ndim-attributes(Attribute that shows the shape of array)
#ndim-parameter(That  defines the shape of array)
import numpy as np
arr=np.array([1,2,3,4,5],ndmin=4)
print(arr)
print(arr.shape)
print(arr.ndim)

[[[[1 2 3 4 5]]]]
(1, 1, 1, 5)
4


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reshaped = arr.reshape(2, 2, 2)  # 3D
print(reshaped)
print("shape:", reshaped.shape)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape: (2, 2, 2)


Identity Matrix::An identity matrix is a square matrix with:

All diagonal elements = 1

All other elements = 0

In [ ]:
import numpy as np

I = np.identity(6)   # 3x3 identity matrix
print(I)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
# np identity-it will always works on square matix (rows==columns)-diagonal =1
#by default the dtype is float
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
np.eye(3,3,dtype=int,k=3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
Broadcasting:automatically expand smaller array to higher dimension array to match shape

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([7,8,9])
print(a+b)

[[ 8 10 12]
 [11 13 15]]


some ways to create arrays

In [ ]:
np.zeros((3,9),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
'''a NumPy function used to create an array filled with a specific value.
It’s very useful when you want an array of a fixed size with the same number everywhere.'''
np.full((6,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [ ]:
#another way
np.ones((5,4))*7

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

Mathematical methods through numpy

In [ ]:
arr=np.array([1,2,3,4,5],ndmin=2)
#methods
print(f'Sum of all elements are:{np.sum(arr)}')
print(f'Mean of all elements are:{np.mean(arr)}')
print(f'variance of all elements are:{np.std(arr)}')
print(f'smallest element:{np.min(arr)}')
print(f'largest element:{np.max(arr)}')
print(f'smallest element:{np.min(arr)}')
print(f'cumulative sum:{np.cumsum(arr)}')

len(arr)

Sum of all elements are:15
Mean of all elements are:3.0
variance of all elements are:1.4142135623730951
smallest element:1
largest element:5
smallest element:1
cumulative sum:[ 1  3  6 10 15]


1

In [ ]:
x=5
y=10
print('the value of x is',x,'and the value of y is',y)
print(f'the value of x is{x} and the value of y is{y} ')

the value of x is 5 and the value of y is 10
the value of x is5 and the value of y is10 


Attributes

Properties of an array (no parentheses () needed).

They give information about the array (like dimensions, shape, size, etc.).

Read-only or descriptive — they don’t perform operations.



In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.ndim)    # 2  (number of dimensions)
print(arr.shape)   # (2, 3) (2 rows, 3 columns)
print(arr.size)    # 6  (total elements)
print(arr.dtype)   # int64 (data type)
print(arr.itemsize) # 8  (bytes per element)
print(arr.nbytes)   # 48 (total bytes = size × itemsize)


2
(2, 3)
6
int64
8
48


Methods

Functions associated with the array (require parentheses ()).

They perform actions/operations (like reshape, sum, mean, flatten, etc.).

In [ ]:
print(arr.sum())        # 21 (sum of all elements)
print(arr.mean())       # 3.5 (average)
print(arr.max())        # 6 (maximum value)
print(arr.min())        # 1 (minimum value)
print(arr.reshape(3, 2)) # reshape to 3x2
print(arr.flatten())    # [1 2 3 4 5 6] (1D view)

21
3.5
6
1
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


Random methods & Pandas

In [36]:
np.random.rand((3))#it will generate 3 values(range-0to1)

array([0.52366482, 0.0255262 , 0.19424834])

In [37]:
np.random.randint(1,10,size=(2,3))

array([[2, 7, 7],
       [7, 2, 4]])

In [38]:
arr=np.array([1,2,3,4,5])
np.random.shuffle(arr)
arr

array([3, 1, 5, 2, 4])

In [44]:
#Matrix manipulation
import numpy as np

# 2D matrix (2x3)
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# 3x3 zero matrix
Z = np.zeros((3,3))

# 3x3 ones matrix
O = np.ones((3,3))

# Identity matrix
I = np.identity(3)

# Matrix filled with a number
F = np.full((2,3), 7)


In [45]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
#onverts a multi-dimensional array into a 1D array.
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [50]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

flat = a.flatten()
print(flat)



[1 2 3 4 5 6]


In [2]:
import numpy as np
x=np.array([1,2])
y=np.array([3,4])
np.vstack((x,y))

array([[1, 2],
       [3, 4]])

In [3]:
np.hstack((x,y))

array([1, 2, 3, 4])

In [6]:
array=np.array([[10,20,30],
               [40,50,60],
               [70,80,90]])
array

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [8]:
print(array[1,1])
print(array[0,2])
print(array[2,:])

50
30
[70 80 90]


In [10]:
array=np.array([20,30,40])
result=np.where (array>25,'High','low')#np.where (condition,true,false)
result

array(['low', 'High', 'High'], dtype='<U4')

In [11]:
a=np.array([1,2,3])
b=a.copy()
c=a.view()
a[0]=150
print(a)
print(b)
print(c)

[150   2   3]
[1 2 3]
[150   2   3]


.copy()-create a new array
.view()-shares the same data
